In [3]:
# imports
from gqlalchemy import Memgraph
import pandas as pd

In [4]:
# connection to graph
memgraph = Memgraph("127.0.0.1", 7687)

In [5]:
# creation of functions for easy Cypher running via VSC

# run and create df
def run_df(query):
    return pd.DataFrame(memgraph.execute_and_fetch(query))


# run and just print
def run_print(query, limit=None):
    results = list(memgraph.execute_and_fetch(query))

    if limit:
        results = results[:limit]

    for row in results:
        print(row)

In [6]:
# Lowie's aviation and legal actions used to construct avation and legal networks
AVIATION_ACTIONS = [
    'traveled with', 'accompanied', 'flew', 'flew with', 'flew on',
    'flew to', 'traveled on aircraft with', 'traveled on private jet of',
    'flew as passenger on', 'traveled on'
]

LEGAL_ACTIONS = [
    'testified before', 'investigated', 'accused', 'arrested', 'charged',
    'prosecuted', 'negotiated non-prosecution agreement with',
    'signed non-prosecution agreement with', 'was charged with', 'was arrested by'
]

## 1.Step 1: "Ground truth" legal actions 
### 1.a. problem in Lowie's analysis: Ghislaine Maxwell (GM) missing
GM is missing in Lowie's bridge notes between his aviation and legal network. 
    - She however appears in aviation network with 15 connection 
    - it is public knowledge that she has been convicted for 20 years. 


#### 1.a.1. as lowie's code for legal network limits to the top 20 
=> first check if GM has any legal actions defined in Lowie's legal action list (she might fall out of top 20)

In [7]:
run_df("""
MATCH (p:Entity)-[r:RELATED_TO]-(other:Entity)
WHERE p.name = 'Ghislaine Maxwell'
  AND r.action IN ['testified before', 'investigated', 'accused', 'arrested', 'charged',
                   'prosecuted', 'negotiated non-prosecution agreement with',
                   'signed non-prosecution agreement with', 'was charged with', 'was arrested by']
RETURN p.name AS entity, count(*) AS legal_connections
""")

Empty DataFrame
Columns: []
Index: []

RESULT: 0 => GM has no legal actions as defined in Lowie's legal action list

#### 1.a.2. Which RELATED_TO actions are linked to GM in the graph? (top 200, by frequency)
(searching undirected relationships, providing GM both as target and actor of action. specific role is specified in return for each action)

In [14]:
run_df("""
MATCH (p:Entity)-[r:RELATED_TO]-(other:Entity)
WHERE p.name = 'Ghislaine Maxwell'
RETURN DISTINCT r.action AS action, 
    CASE WHEN startNode(r) = p THEN 'actor' ELSE 'target' END AS role,
    count(*) AS n
ORDER BY n DESC
LIMIT 100
""")

                                            action    role   n
0                                    sent email to  target  34
1                                        recruited   actor  17
2                                    sent email to   actor  14
3                                       introduced   actor  14
4                                         attended   actor  11
..                                             ...     ...  ..
95                                 testified about   actor   2
96                       inquired about service on  target   2
97                directed victim to have sex with   actor   2
98                      interviewed for employment   actor   2
99  had sexual encounters with victims arranged by  target   2

[100 rows x 3 columns]

RESULT: list fed to Claude, to make a selection of actions with legal nature => 3 categories returned:

(1) GM as defendant (n=count):  
"served subpoena to" (6) 
"served subpoena on" (3) 
"served with subpoena" (2) 
"challenged exclusion of evidence regarding plaintiff's" (6) 
"opposed motions in limine filed by" (2) 
"argued before court regarding" (2) 
"rescheduled deposition of" (3) 
"scheduled deposition for" (2) 
"attempted to depose" (2) 
"sought to introduce evidence regarding" (2) 
"invoked privilege against self-incrimination" (1) 
"accused of participating in" (2)

(2) GM as victim/plaintiff (n=count):
"sued" (7) 
"filed defamation lawsuit against" (5)
"filed defamation suit against" (4) 
"filed civil lawsuit against" (2) 
"filed federal civil suit against" (2)
"filed lawsuit against" (2)
"filed suit against" (2) 
"filed complaint against" (2) 
"sued for defamation" (2) 
"filed legal brief as attorney for" (2) 

(3) other (can be both as defendant or victim/plaintiff): 
"questioned" (3)
"interviewed" (3) 
"testified about" (2)
"identified" (3) 
"settled lawsuit with" (5)

CONCLUSIONS: 
    - GM's criminal conviction seems to be virtually absent from the data. Possible explanation: GM was convicted in DEC 2021. However many of the released documents by the house of representation cover the periode before her arrest in 2020. In that period GM had civil law suites with e.g. Giuffre: Giuffre v. Maxwell (2015-2017) (Giuffre filed a civil defamation lawsuit against GM, alleging GM had called her claims about Epstein's trafficking 'obvious lies'. The case was settled in 2017.)

    - vs. Lowie's legal_actions list: 
            (1) civil vs criminal law: LLM seems to have used terminology of civil law suites rather than those of criminal law suites, for GM. Lowie's legal network focussed mainly on criminal law terminology <=> we need to rebuild the legal actions list. We will examine RELATED_TO actions linked to other figures with documented legal involvement in the Epstein case (public knowledge) (our ground truth figures) => we use these to extend legal actions list with both civil and criminal terms as they actually appear in the dataset.

            (2) searching with IN vs CONTAINS in WHERE statement: e.g. "accused" part of Lowie's list, however due to the use of IN in the where statement, Cypher only searches for exact matches. => search made anew, using CONTAIN instead of IN in WHERE statement. (including other legal_actions from Lowie's list)

In [18]:
run_print("""
MATCH (p:Entity)-[r:RELATED_TO]-(other:Entity)
WHERE p.name = 'Ghislaine Maxwell'
AND (
    toLower(r.action) CONTAINS 'testified'
    OR toLower(r.action) CONTAINS 'investigated'
    OR toLower(r.action) CONTAINS 'accused'
    OR toLower(r.action) CONTAINS 'arrested'
    OR toLower(r.action) CONTAINS 'charged'
    OR toLower(r.action) CONTAINS 'prosecuted'
    OR toLower(r.action) CONTAINS 'non-prosecution'
    OR toLower(r.action) CONTAINS 'charged'
)
RETURN r.action AS action, count(*) AS n
ORDER BY n DESC
""")

{'action': 'accused of participating in', 'n': 2}
{'action': 'testified about', 'n': 2}
{'action': 'accused of procuring', 'n': 1}
{'action': 'testified to', 'n': 1}
{'action': 'testified that she worked for', 'n': 1}
{'action': 'accused of helping recruit and sexually exploit', 'n': 1}
{'action': 'testified at deposition regarding knowledge about', 'n': 1}
{'action': 'testified', 'n': 1}
{'action': 'testified that she did not look at', 'n': 1}
{'action': 'testified that she was unsure about', 'n': 1}
{'action': 'testified at deposition that she never read prior to January 2015', 'n': 1}
{'action': 'testified regarding relationship with', 'n': 1}

RESULTS: GM would have appeared in Lowie's legal network if search would have been with CONTAIN in WHERE statement. 

CONCLUSION: 
(2) important to search with CONTAIN in WHERE statement in legal_network, and to adapt terminology accordingly.

### 1.b Rebuilding legal action list: analyse RELATED_TO legal actions of known figures with publicly known legal involvement linked to Epstein's operations 
(based on public record, verified against the data):

Chosen public figures: 
Jeffrey Epstein — arrested 2019, died in custody
Ghislaine Maxwell — convicted (20 years, 2021)
Jean-Luc Brunel — arrested, died in custody (2022)
Alfredo Rodriguez — convicted of obstruction (18 months)
Virginia Roberts Giuffre — central plaintiff in multiple civil proceedings
Prince Andrew — settled civil lawsuit with Giuffre (2022)
Alan Dershowitz — named in civil proceedings by Giuffre
Sarah Kellen — named co-conspirator in 2008 NPA, named in civil lawsuits
Adriana Ross — named co-conspirator in 2008 NPA, named in civil lawsuits
Nadia Marcinkova — named co-conspirator in 2008 NPA, named in civil lawsuits
Lesley Groff — named co-conspirator in 2008 NPA, named in civil lawsuits

#### 1.b.1 For each figure: verify name variants, aliases, and possible duplicate nodes in the dataset

For example: for Epstein himself.

In [19]:
# looking for all entities that might represent epstein himself in the graph
run_print("""
MATCH (e:Entity)
WHERE e.name = 'Jeffrey Epstein'
   OR e.name = 'Epstein'
   OR e.name = 'J. Epstein'
   OR e.name = 'Jeff Epstein'
RETURN e.name, e.entity_type, count(*) AS n
""")

{'e.name': 'Jeffrey Epstein', 'e.entity_type': 'victim', 'n': 1}
{'e.name': 'Jeff Epstein', 'e.entity_type': None, 'n': 1}
{'e.name': 'Epstein', 'e.entity_type': None, 'n': 1}

In [20]:
# looking for all aliases that might be linked to these entity nodes
run_print("""
MATCH (a:Alias)-[:ALIAS_OF]->(e:Entity)
WHERE e.name IN ['Jeffrey Epstein', 'Jeff Epstein', 'Epstein']
RETURN e.name AS canonical_name, a.name AS alias
ORDER BY e.name
""")

{'canonical_name': 'Epstein', 'alias': 'Epstein'}
{'canonical_name': 'Jeff Epstein', 'alias': 'Jeff Epstein'}
{'canonical_name': 'Jeffrey Epstein', 'alias': 'Epstein Jeffrey'}
{'canonical_name': 'Jeffrey Epstein', 'alias': 'J'}
{'canonical_name': 'Jeffrey Epstein', 'alias': 'Jeff'}
{'canonical_name': 'Jeffrey Epstein', 'alias': 'Jeffrey'}
{'canonical_name': 'Jeffrey Epstein', 'alias': 'Jeffrey E.'}
{'canonical_name': 'Jeffrey Epstein', 'alias': 'Jeffrey E. Epstein'}
{'canonical_name': 'Jeffrey Epstein', 'alias': 'Jeffrey Edward Epstein'}
{'canonical_name': 'Jeffrey Epstein', 'alias': 'Jeffrey Epstein'}
{'canonical_name': 'Jeffrey Epstein', 'alias': 'jee'}

RESULTS: 
3 entity nodes that represent epstein. Only to one of them aliases are linked (looking at the different amount of Aliases linked, first node herunder might be kind of the "main Epstein node").
    (1) "Jeffrey Epstein" - with aliases: 
        'Jeffrey Edward Epstein', 'Jeffrey E. Epstein', 'Jeffrey E.', 'Jeffrey', 'Jeff', 'J', 'jee', 'Epstein Jeffrey'
    (2) "Jeff Epstein"   (no aliases)
    (3) "Epstein" (no aliases)

In [24]:
# search for our other "ground truth"-figures: 
run_print("""
MATCH (a:Alias)-[:ALIAS_OF]->(e:Entity)
WHERE toLower(e.name) CONTAINS 'maxwell'
   OR toLower(e.name) CONTAINS 'brunel'
   OR toLower(e.name) CONTAINS 'rodriguez'
   OR toLower(e.name) CONTAINS 'giuffre'
   OR toLower(e.name) CONTAINS 'virginia roberts'
   OR toLower(e.name) CONTAINS 'prince andrew'
   OR toLower(e.name) CONTAINS 'dershowitz'
   OR toLower(e.name) CONTAINS 'kellen'
   OR toLower(e.name) CONTAINS 'marcinkova'
   OR toLower(e.name) CONTAINS 'marcinko'
   OR toLower(e.name) CONTAINS 'lesley groff'
   OR toLower(e.name) CONTAINS 'adriana'
RETURN e.name AS canonical_name, a.name AS alias
ORDER BY e.name
""")

{'canonical_name': 'Adriana Mucinska', 'alias': 'Adriana Mucinska'}
{'canonical_name': 'Adriana Mucinska Ross', 'alias': 'Adriana Mucinska Ross'}
{'canonical_name': 'Adriana Mucinska Ross', 'alias': 'Adriana Ross'}
{'canonical_name': 'Alan Dershowitz and Jeffrey Epstein', 'alias': 'Alan Dershowitz and Jeffrey Epstein'}
{'canonical_name': 'Alan Dershowitz and Matthew Hale', 'alias': 'Alan Dershowitz and Matthew Hale'}
{'canonical_name': 'Alan Dershowitz and Prince Andrew', 'alias': 'Alan Dershowitz and Prince Andrew'}
{'canonical_name': 'Alan Dershowitz and Rebecca Boylan', 'alias': 'Alan Dershowitz and Rebecca Boylan'}
{'canonical_name': 'Alan Dershowitz and Tatiana', 'alias': 'Alan Dershowitz and Tatiana'}
{'canonical_name': 'Alan Dershowitz and brother Nathan', 'alias': 'Alan Dershowitz and brother Nathan'}
{'canonical_name': 'Alan Dershowitz and classmate', 'alias': 'Alan Dershowitz and classmate'}
{'canonical_name': 'Alan Dershowitz and family', 'alias': 'Alan Dershowitz and family'}
{'canonical_name': 'Alan Dershowitz around neck', 'alias': 'Alan Dershowitz around neck'}
{'canonical_name': 'Alan Dershowitz as appellate counsel after assessment', 'alias': 'Alan Dershowitz as appellate counsel after assessment'}
{'canonical_name': 'Alan Dershowitz as appellate lawyer for prosecution', 'alias': 'Alan Dershowitz as appellate lawyer for prosecution'}
{'canonical_name': 'Alan Dershowitz from prison phone line to discuss appeal', 'alias': 'Alan Dershowitz from prison phone line to discuss appeal'}
{'canonical_name': 'Alan Dershowitz had sex with her at least six times starting when she was 16', 'alias': 'Alan Dershowitz had sex with her at least six times starting when she was 16'}
{'canonical_name': 'Alan Dershowitz observed her in sexual activity with Epstein', 'alias': 'Alan Dershowitz observed her in sexual activity with Epstein'}
{'canonical_name': 'Alan Dershowitz occurred at multiple Epstein properties and on his airplane', 'alias': 'Alan Dershowitz occurred at multiple Epstein properties and on his airplane'}
{'canonical_name': 'Alan Dershowitz on John Connolly appeal', 'alias': 'Alan Dershowitz on John Connolly appeal'}
{'canonical_name': 'Alan Dershowitz retainer to represent Gaddafi', 'alias': 'Alan Dershowitz retainer to represent Gaddafi'}
{'canonical_name': 'Alan Dershowitz to Martin Luther King Jr. speech', 'alias': 'Alan Dershowitz to Martin Luther King Jr. speech'}
{'canonical_name': 'Alan Dershowitz to represent Igal Amir', 'alias': 'Alan Dershowitz to represent Igal Amir'}
{'canonical_name': 'Alan Dershowitz to represent Mike Tyson on appeal', 'alias': 'Alan Dershowitz to represent Mike Tyson on appeal'}
{'canonical_name': 'Alan Dershowitz to sexual abuse of minor girls', 'alias': 'Alan Dershowitz to sexual abuse of minor girls'}
{'canonical_name': 'Alan Dershowitz vacation time', 'alias': 'Alan Dershowitz vacation time'}
{'canonical_name': "Alan Dershowitz's Stanley case application argument", 'alias': "Alan Dershowitz's Stanley case application argument"}
{'canonical_name': "Alan Dershowitz's activities at Epstein's home", 'alias': "Alan Dershowitz's activities at Epstein's home"}
{'canonical_name': "Alan Dershowitz's assessment of his role in Lennon case", 'alias': "Alan Dershowitz's assessment of his role in Lennon case"}
{'canonical_name': "Alan Dershowitz's conduct at Epstein's home", 'alias': "Alan Dershowitz's conduct at Epstein's home"}
{'canonical_name': "Alan Dershowitz's counsel", 'alias': "Alan Dershowitz's counsel"}
{'canonical_name': "Alan Dershowitz's father", 'alias': "Alan Dershowitz's father"}
{'canonical_name': "Alan Dershowitz's grandmother", 'alias': "Alan Dershowitz's grandmother"}
{'canonical_name': "Alan Dershowitz's mother", 'alias': "Alan Dershowitz's mother"}
{'canonical_name': "Alan Dershowitz's motion to intervene", 'alias': "Alan Dershowitz's motion to intervene"}
{'canonical_name': "Alan Dershowitz's motion to seal court records", 'alias': "Alan Dershowitz's motion to seal court records"}
{'canonical_name': "Alan Dershowitz's parents", 'alias': "Alan Dershowitz's parents"}
{'canonical_name': "Alan Dershowitz's presence at Epstein's residence with young women", 'alias': "Alan Dershowitz's presence at Epstein's residence with young women"}
{'canonical_name': "Alan Dershowitz's public statements and deposition testimony", 'alias': "Alan Dershowitz's public statements and deposition testimony"}
{'canonical_name': "Alan Dershowitz's question about religious observance", 'alias': "Alan Dershowitz's question about religious observance"}
{'canonical_name': "Alan Dershowitz's son Elon to Supreme Court", 'alias': "Alan Dershowitz's son Elon to Supreme Court"}
{'canonical_name': "Alan Dershowitz's team", 'alias': "Alan Dershowitz's team"}
{'canonical_name': "Alan Dershowitz's visits and activities at Epstein's house", 'alias': "Alan Dershowitz's visits and activities at Epstein's house"}
{'canonical_name': 'Alan Dershowitz, Anatoly Sharansky, and Mikhail Gorbachev', 'alias': 'Alan Dershowitz, Anatoly Sharansky, and Mikhail Gorbachev'}
{'canonical_name': 'Alan Dershowitz, Gerald Lefcourt, Ken Starr', 'alias': 'Alan Dershowitz, Gerald Lefcourt, Ken Starr'}
{'canonical_name': 'Alan Dershowitz, Gerald Lefcourt, Roy Black, Kenneth Starr, Guy Lewis, Martin Weinberger', 'alias': 'Alan Dershowitz, Gerald Lefcourt, Roy Black, Kenneth Starr, Guy Lewis, Martin Weinberger'}
{'canonical_name': 'Alan Dershowitz; Leslie Wexner', 'alias': 'Alan Dershowitz; Leslie Wexner'}
{'canonical_name': 'Alan M. Dershowitz', 'alias': 'Professor Alan Dershowitz'}
{'canonical_name': 'Alan M. Dershowitz', 'alias': 'Dershowitz'}
{'canonical_name': 'Alan M. Dershowitz', 'alias': 'Alan M. Dershowitz'}
{'canonical_name': 'Alan M. Dershowitz', 'alias': 'Alan'}
{'canonical_name': 'Alan M. Dershowitz', 'alias': 'Alan Dershowitz'}
{'canonical_name': "Alan M. Dershowitz's counsel", 'alias': "Alan M. Dershowitz's counsel"}
{'canonical_name': 'Alfonso Rodriguez', 'alias': 'Alfonso Rodriguez'}
{'canonical_name': 'Alfredo Rodriguez', 'alias': 'Fred'}
{'canonical_name': 'Alfredo Rodriguez', 'alias': 'Alfredo Rodriguez (household account manager)'}
{'canonical_name': 'Alfredo Rodriguez', 'alias': 'Alfredo Rodriguez'}
{'canonical_name': 'Barack Obama and David Dershowitz', 'alias': 'Barack Obama and David Dershowitz'}
{'canonical_name': 'Bill Clinton and Prince Andrew', 'alias': 'Bill Clinton and Prince Andrew'}
{'canonical_name': 'Bill Clinton, Al Gore, senators, scientists, Alan Dershowitz', 'alias': 'Bill Clinton, Al Gore, senators, scientists, Alan Dershowitz'}
{'canonical_name': 'Bill Clinton, Ghislaine Maxwell, and young female associates', 'alias': 'Bill Clinton, Ghislaine Maxwell, and young female associates'}
{'canonical_name': 'Bill Clinton, Jeffrey Epstein, Ghislaine Maxwell', 'alias': 'Bill Clinton, Jeffrey Epstein, Ghislaine Maxwell'}
{'canonical_name': 'Bill Clinton, Prince Andrew, Donald Trump, and hundreds of other high-profile individuals', 'alias': 'Bill Clinton, Prince Andrew, Donald Trump, and hundreds of other high-profile individuals'}
{'canonical_name': 'Bill Clinton, Prince Andrew, Donald Trump, and numerous other prominent figures', 'alias': 'Bill Clinton, Prince Andrew, Donald Trump, and numerous other prominent figures'}
{'canonical_name': 'Bill Clinton, Prince Andrew, Ehud Barak, Andres Pastrana Arango, Lawrence Summers, Ron Burkle, Kevin Spacey, Chris Tucker', 'alias': 'Bill Clinton, Prince Andrew, Ehud Barak, Andres Pastrana Arango, Lawrence Summers, Ron Burkle, Kevin Spacey, Chris Tucker'}
{'canonical_name': 'Bill Clinton, Prince Andrew, Ehud Barak, Bill Richardson, Larry Summers', 'alias': 'Bill Clinton, Prince Andrew, Ehud Barak, Bill Richardson, Larry Summers'}
{'canonical_name': 'Bill Clinton, Sandy Berger, Andres Pastrana, Alan Dershowitz', 'alias': 'Bill Clinton, Sandy Berger, Andres Pastrana, Alan Dershowitz'}
{'canonical_name': 'Bradley Edwards, Paul Cassell, and Alan Dershowitz', 'alias': 'Bradley Edwards, Paul Cassell, and Alan Dershowitz'}
{'canonical_name': 'Bradley J. Edwards and Paul G. Cassell vs. Alan M. Dershowitz', 'alias': 'Bradley J. Edwards and Paul G. Cassell vs. Alan M. Dershowitz'}
{'canonical_name': 'Cassell-Edwards-Dershowitz litigation', 'alias': 'Cassell-Edwards-Dershowitz litigation'}
{'canonical_name': 'Cassell/Edwards v. Dershowitz', 'alias': 'Cassell/Edwards v. Dershowitz'}
{'canonical_name': 'Court (depostion in Virginia Giuffre v. Ghislaine Maxwell)', 'alias': 'Court (depostion in Virginia Giuffre v. Ghislaine Maxwell)'}
{'canonical_name': 'Court proceedings in Edwards v. Dershowitz', 'alias': 'Court proceedings in Edwards v. Dershowitz'}
{'canonical_name': 'Daily Beast article on Epstein, Dershowitz, and sex trafficking allegations', 'alias': 'Daily Beast article on Epstein, Dershowitz, and sex trafficking allegations'}
{'canonical_name': "Declaration in support of Petitioners' response to Dershowitz motion", 'alias': "Declaration in support of Petitioners' response to Dershowitz motion"}
{'canonical_name': 'Deposition (Virginia Giuffre v. Ghislaine Maxwell)', 'alias': 'Deposition (Virginia Giuffre v. Ghislaine Maxwell)'}
{'canonical_name': "Dershowitz's Motion for Leave to File Supplemental Reply", 'alias': "Dershowitz's Motion for Leave to File Supplemental Reply"}
{'canonical_name': "Dershowitz's kosher deli and adult entertainment venues", 'alias': "Dershowitz's kosher deli and adult entertainment venues"}
{'canonical_name': "Dershowitz's legal team", 'alias': "Dershowitz's legal team"}
{'canonical_name': "Dershowitz's motion to seal", 'alias': "Dershowitz's motion to seal"}
{'canonical_name': "Dershowitz's original I Am Curious Yellow theory more than Supreme Court doctrine", 'alias': "Dershowitz's original I Am Curious Yellow theory more than Supreme Court doctrine"}
{'canonical_name': "Dershowitz's theory in Miller v. California", 'alias': "Dershowitz's theory in Miller v. California"}
{'canonical_name': 'Donald Trump and Alan Dershowitz', 'alias': 'Donald Trump and Alan Dershowitz'}
{'canonical_name': 'Donald Trump, Bill Clinton, and Prince Andrew', 'alias': 'Donald Trump, Bill Clinton, and Prince Andrew'}
{'canonical_name': 'Edwards and Cassells vs. Dershowitz case', 'alias': 'Edwards and Cassells vs. Dershowitz case'}
{'canonical_name': 'Edwards v. Dershowitz case', 'alias': 'Edwards v. Dershowitz defamation case'}
{'canonical_name': 'Edwards v. Dershowitz case', 'alias': 'Edwards v. Dershowitz case'}
{'canonical_name': 'Edwards, Cassell, and Ms. Giuffre', 'alias': 'Edwards, Cassell, and Ms. Giuffre'}
{'canonical_name': 'Elon Dershowitz', 'alias': 'Elon Dershowitz'}
{'canonical_name': 'Elon Dershowitz', 'alias': "Elon Dershowitz (Alan's son)"}
{'canonical_name': 'G Maxwell', 'alias': 'G Maxwell'}
{'canonical_name': 'GMAX, Brian Basham, Ian Maxwell, Kevin Maxwell, Gareth Thompson', 'alias': 'GMAX, Brian Basham, Ian Maxwell, Kevin Maxwell, Gareth Thompson'}
{'canonical_name': 'Ghislaine Maxwell', 'alias': 'Ghislaine'}
{'canonical_name': 'Ghislaine Maxwell', 'alias': 'Ghislaine Maxwell'}
{'canonical_name': 'Ghislaine Maxwell', 'alias': 'Maxwell'}
{'canonical_name': 'Ghislaine Maxwell and Leslie Wexner regarding service', 'alias': 'Ghislaine Maxwell and Leslie Wexner regarding service'}
{'canonical_name': 'Ghislaine Maxwell and Prince Andrew', 'alias': 'Ghislaine Maxwell and Prince Andrew'}
{'canonical_name': 'Ghislaine Maxwell as managing director', 'alias': 'Ghislaine Maxwell as managing director'}
{'canonical_name': 'Ghislaine Maxwell case', 'alias': 'Ghislaine Maxwell case'}
{'canonical_name': "Ghislaine Maxwell's 39th birthday", 'alias': "Ghislaine Maxwell's 39th birthday"}
{'canonical_name': "Ghislaine Maxwell's 39th birthday", 'alias': "Ghislaine Maxwell's 39th birthday at Sandringham estate"}
{'canonical_name': "Ghislaine Maxwell's attorney", 'alias': "Ghislaine Maxwell's attorney"}
{'canonical_name': "Ghislaine Maxwell's relationship status", 'alias': "Ghislaine Maxwell's relationship status"}
{'canonical_name': 'Ghislaine Maxwell, Brian Basham, Ian Maxwell, Kevin Maxwell, Gareth Thompson', 'alias': 'Ghislaine Maxwell, Brian Basham, Ian Maxwell, Kevin Maxwell, Gareth Thompson'}
{'canonical_name': 'Ghislaine Maxwell, Jean Luc Brunel, Rodriguez, and Marcinkova', 'alias': 'Ghislaine Maxwell, Jean Luc Brunel, Rodriguez, and Marcinkova'}
{'canonical_name': 'Ghislaine Maxwell, Ross Gow, others', 'alias': 'Ghislaine Maxwell, Ross Gow, others'}
{'canonical_name': 'Ghislaine Maxwell, Virginia Roberts, and ET', 'alias': 'Ghislaine Maxwell, Virginia Roberts, and ET'}
{'canonical_name': 'Ghislaine Maxwell, internal team', 'alias': 'Ghislaine Maxwell, internal team'}
{'canonical_name': 'Giovanni Rodriguez', 'alias': 'Giovanni Rodriguez'}
{'canonical_name': 'Giuffre v. Maxwell', 'alias': 'Maxwell case'}
{'canonical_name': 'Giuffre v. Maxwell', 'alias': 'Giuffre v. Maxwell litigation'}
{'canonical_name': 'Giuffre v. Maxwell', 'alias': 'Giuffre v. Maxwell case appeal'}
{'canonical_name': 'Giuffre v. Maxwell', 'alias': 'Giuffre v. Maxwell case'}
{'canonical_name': 'Giuffre v. Maxwell', 'alias': 'Giuffre v. Maxwell'}
{'canonical_name': 'Ian Maxwell, Kevin Maxwell, Brian Basham, Gareth Thompson', 'alias': 'Ian Maxwell, Kevin Maxwell, Brian Basham, Gareth Thompson'}
{'canonical_name': 'Isabel Maxwell', 'alias': 'Isabel Maxwell'}
{'canonical_name': "Jane Doe #3's allegations against Dershowitz (HOUSE_OVERSIGHT_015545)", 'alias': "Jane Doe #3's allegations against Dershowitz (HOUSE_OVERSIGHT_015545)"}
{'canonical_name': 'Jane Doe 3 (Ms. Giuffre) (HOUSE_OVERSIGHT_015630)', 'alias': 'Jane Doe 3 (Ms. Giuffre) (HOUSE_OVERSIGHT_015630)'}
{'canonical_name': 'Jane Doe 3 and Jane Doe 4 joining Giuffre litigation (HOUSE_OVERSIGHT_014652) (HOUSE_OVERSIGHT_014652)', 'alias': 'Jane Doe 3 and Jane Doe 4 joining Giuffre litigation (HOUSE_OVERSIGHT_014652) (HOUSE_OVERSIGHT_014652)'}
{'canonical_name': 'Jean Luc Brunel', 'alias': 'Jean Luc Brune'}
{'canonical_name': 'Jean Luc Brunel', 'alias': 'Jean Luc Brunel'}
{'canonical_name': 'Jean Luc Brunel', 'alias': 'Jean Luc Brunel and MC2 modeling agency'}
{'canonical_name': 'Jean Luc Brunel', 'alias': 'Jean Luc Bruhnel'}
{'canonical_name': 'Jean Luc Brunel', 'alias': 'Jean Luc Brunel, MC2 modeling agency'}
{'canonical_name': 'Jean Luc Brunel, Ghislaine Maxwell, Alfonso Rodriguez, Nadia Marcinkova', 'alias': 'Jean Luc Brunel, Ghislaine Maxwell, Alfonso Rodriguez, Nadia Marcinkova'}
{'canonical_name': 'Jean-Luc Brunel', 'alias': 'Jean-Luc Brunel and MC2 Model & Talent Miami'}
{'canonical_name': 'Jean-Luc Brunel', 'alias': 'false and defamatory information about Jean-Luc Brunel and MC2'}
{'canonical_name': 'Jean-Luc Brunel', 'alias': 'false and disparaging information about Jean-Luc Brunel and MC2'}
{'canonical_name': 'Jean-Luc Brunel', 'alias': 'three 12-year-old girls purchased by Jean-Luc Brunel from their parents'}
{'canonical_name': 'Jean-Luc Didier Henri-Rene Brunel', 'alias': 'Jean-Luc Brunel'}
{'canonical_name': 'Jean-Luc Didier Henri-Rene Brunel', 'alias': 'Jean-Luc Didier Henri-Rene Brunel'}
{'canonical_name': 'Jean-Luc Didier Henri-Rene Brunel', 'alias': 'Brunel'}
{'canonical_name': 'Jeffrey Epstein and Alan Dershowitz', 'alias': 'Jeffrey Epstein and Alan Dershowitz'}
{'canonical_name': 'Jeffrey Epstein and Ghislaine Maxwell', 'alias': 'Jeffrey Epstein and Ghislaine Maxwell'}
{'canonical_name': 'Jeffrey Epstein and associates including Prince Andrew and Alan Dershowitz', 'alias': 'Jeffrey Epstein and associates including Prince Andrew and Alan Dershowitz'}
{'canonical_name': "Jeffrey Epstein's sex trafficking operation and Dershowitz involvement", 'alias': "Jeffrey Epstein's sex trafficking operation and Dershowitz involvement"}
{'canonical_name': 'Jeffrey Epstein, Alan Dershowitz, Prince Andrew', 'alias': 'Jeffrey Epstein, Alan Dershowitz, Prince Andrew'}
{'canonical_name': 'Jeffrey Epstein, Alan Dershowitz, Prince Andrew, and other men', 'alias': 'Jeffrey Epstein, Alan Dershowitz, Prince Andrew, and other men'}
{'canonical_name': 'Jeffrey Epstein, Ghislaine Maxwell, Nadia Marcinkova, and Sarah Kellen', 'alias': 'Jeffrey Epstein, Ghislaine Maxwell, Nadia Marcinkova, and Sarah Kellen'}
{'canonical_name': 'Jeffrey Epstein, Haley Robson, Sarah Kellen', 'alias': 'Jeffrey Epstein, Haley Robson, Sarah Kellen'}
{'canonical_name': 'Jordan Maxwell', 'alias': 'Jordan Maxwell'}
{'canonical_name': 'Juan Alessi and Alfredo Rodriguez', 'alias': 'Juan Alessi and Alfredo Rodriguez'}
{'canonical_name': 'Kellen', 'alias': 'Kellen'}
{'canonical_name': 'Kevin Maxwell', 'alias': 'Kevin Maxwell'}
{'canonical_name': 'Lesley Groff', 'alias': 'Lesley'}
{'canonical_name': 'Lesley Groff', 'alias': 'Lesley Groff'}
{'canonical_name': 'Marcinkova', 'alias': 'Marcinkova'}
{'canonical_name': "Marilyn Dershowitz (Alan's sister-in-law)", 'alias': "Marilyn Dershowitz (Alan's sister-in-law)"}
{'canonical_name': 'Maxwell family', 'alias': 'Maxwell family'}
{'canonical_name': 'Mr. Dershowitz', 'alias': 'Mr. Dershowitz'}
{'canonical_name': 'Ms. Giuffre', 'alias': 'Ms. Giuffre'}
{'canonical_name': "Ms. Giuffre's affidavit", 'alias': "Ms. Giuffre's affidavit"}
{'canonical_name': "Ms. Giuffre's counsel", 'alias': "Ms. Giuffre's counsel"}
{'canonical_name': 'Nada Marcinkova', 'alias': 'Nada Marcinkova'}
{'canonical_name': 'Nadia Marcinkova', 'alias': 'Nadia'}
{'canonical_name': 'Nadia Marcinkova', 'alias': 'Nadia Marcinkova'}
{'canonical_name': 'Narciso Rodriguez', 'alias': 'Narciso Rodriguez'}
{'canonical_name': 'Natalia Marcinkova', 'alias': 'Natalia Marcinkova'}
{'canonical_name': 'Paul Cassell, Edwards, and Ms. Giuffre', 'alias': 'Paul Cassell, Edwards, and Ms. Giuffre'}
{'canonical_name': 'Pink Jean Luc Brunel', 'alias': 'Pink Jean Luc Brunel'}
{'canonical_name': 'Plaintiff Brunel', 'alias': 'Plaintiff Brunel'}
{'canonical_name': 'Prince Andrew', 'alias': 'cocktail party attended by Prince Andrew'}
{'canonical_name': 'Prince Andrew and Alan Dershowitz', 'alias': 'Prince Andrew and Alan Dershowitz'}
{'canonical_name': 'Prince Andrew and Alan Dershowitz as participants in sex trafficking', 'alias': 'Prince Andrew and Alan Dershowitz as participants in sex trafficking'}
{'canonical_name': 'Prince Andrew and Donald Trump', 'alias': 'Prince Andrew and Donald Trump'}
{'canonical_name': 'Prince Andrew and Ghislaine Maxwell', 'alias': 'Prince Andrew and Ghislaine Maxwell'}
{'canonical_name': 'Prince Andrew and Jeffrey Epstein', 'alias': 'Prince Andrew and Jeffrey Epstein'}
{'canonical_name': 'Prince Andrew to Jeffrey Epstein', 'alias': 'Prince Andrew to Jeffrey Epstein'}
{'canonical_name': 'Prince Andrew, Alan Dershowitz', 'alias': 'Prince Andrew, Alan Dershowitz'}
{'canonical_name': 'Prince Andrew, Donald Trump, Harvey Weinstein, David Copperfield', 'alias': 'Prince Andrew, Donald Trump, Harvey Weinstein, David Copperfield'}
{'canonical_name': 'Prince Andrew, Duke of York', 'alias': 'substantial publicity regarding Prince Andrew and Dershowitz'}
{'canonical_name': 'Prince Andrew, Duke of York', 'alias': 'photographs documenting relationship with Prince Andrew'}
{'canonical_name': 'Prince Andrew, Duke of York', 'alias': 'new lawsuit filing with allegations connecting to Prince Andrew'}
{'canonical_name': 'Prince Andrew, Duke of York', 'alias': 'Andrew'}
{'canonical_name': 'Prince Andrew, Duke of York', 'alias': 'Andrew (Prince Andrew)'}
{'canonical_name': 'Prince Andrew, Duke of York', 'alias': 'Alfredo Rodriguez regarding Prince Andrew'}
{'canonical_name': 'Prince Andrew, Duke of York', 'alias': 'Virginia Roberts and Prince Andrew'}
{'canonical_name': 'Prince Andrew, Duke of York', 'alias': 'Epstein to Prince Andrew and others'}
{'canonical_name': 'Prince Andrew, Duke of York', 'alias': 'Prince Andrew, Duke of York'}
{'canonical_name': 'Prince Andrew, Duke of York', 'alias': 'Prince Andrew with teenage girl'}
{'canonical_name': 'Prince Andrew, Duke of York', 'alias': 'Prince Andrew seated with narrator and Johanna'}

RESULTS: 
- List was fed to Claude to filter out relevant nodes (referring to actual persons): 
    (1) GM: 
    'Ghislaine Maxwell' — aliases: 'Maxwell', 'Ghislaine'
    'G Maxwell' — no alias
    
    (2) Brunel:
    'Jean-Luc Didier Henri-Rene Brunel' — aliases: 'Jean-Luc Brunel', 'Brunel'
    'Jean Luc Brunel' — aliases: 'Jean Luc Bruhnel', 'Jean Luc Brune'
    'Jean-Luc Brunel' — no alias

    (3) Rodriguez:
    'Alfredo Rodriguez' — aliases: 'Alfredo Rodriguez (household account manager)', 'Fred'
    'Alfonso Rodriguez' — no alias (possibly a duplicate)

    (4) Giuffre:
    'Virginia Roberts Giuffre' — aliases: 'Virginia Roberts', 'Virginia L. Giuffre', 'Virginia Roberts (age 17)' (and more)
    'Virginia L. Giuffre' — aliases: 'Virginia Giuffre', 'Virginia Giuffre/Roberts'
    'Virginia' - no aliases

    (5) Prince Andrew:
    'Prince Andrew, Duke of York' — aliases: 'Andrew', 'Prince Andrew', 'Prince Andrew (Duke of York)', (and more)

    (6) Dershowitz:
    'Alan M. Dershowitz' — aliases: 'Alan Dershowitz', 'Dershowitz', 'Alan', 'Professor Alan Dershowitz'
    'Professor Dershowitz' — no aliases

    (7) Kellen:
    'Sarah Kellen' — aliases: 'Sarah', 'Kellen'

    (8) Ross:
    'Adriana Mucinska Ross' — aliases: 'Adriana Ross'
    'Adriana Mucinska' — no aliases
    
    (9) Marcinkova:
    'Nadia Marcinkova' — aliases: 'Nadia', 'Marcinkova'
    'Nada Marcinkova' — no aliases
    'Natalia Marcinkova' — no aliases

    (10) Groff:
    'Lesley Groff' — aliases: 'Lesley'


CONCLUSION: 
- our ground truth figures list with all nodes:

In [28]:
ground_truth_figures = {
    'Epstein': ['Jeffrey Epstein', 'Jeff Epstein', 'Epstein'],
    'Maxwell': ['Ghislaine Maxwell', 'G Maxwell'],
    'Brunel': ['Jean-Luc Brunel', 'Jean Luc Brunel', 
               'Jean-Luc Didier Henri-Rene Brunel'],
    'Rodriguez': ['Alfredo Rodriguez', 'Alfonso Rodriguez'],
    'Giuffre': ['Virginia Roberts Giuffre', 'Virginia L. Giuffre', 'Virginia'],
    'Prince Andrew': ['Prince Andrew, Duke of York'],
    'Dershowitz': ['Alan M. Dershowitz', 'Professor Dershowitz'],
    'Kellen': ['Sarah Kellen'],
    'Ross': ['Adriana Mucinska Ross', 'Adriana Mucinska'],
    'Marcinkova': ['Nadia Marcinkova', 'Nada Marcinkova', 'Natalia Marcinkova'],
    'Groff': ['Lesley Groff']
}

#### 1.b.2. Extract their legal actions from the graph to build an empirically grounded, extended LEGAL_ACTIONS list

In [31]:
# extracting for each ground_truth_figure top 200 actions (in general) first: 
results = []
for group, names in ground_truth_figures.items():
    for name in names:
        df = run_print(f"""
        MATCH (p:Entity)-[r:RELATED_TO]-(other:Entity)
        WHERE p.name = '{name}'
        RETURN p.name AS person, r.action AS action, count(*) AS n
        ORDER BY n DESC
        LIMIT 300
        """)

{'person': 'Jeffrey Epstein', 'action': 'sent email to', 'n': 5426}
{'person': 'Jeffrey Epstein', 'action': 'sent message to', 'n': 1063}
{'person': 'Jeffrey Epstein', 'action': 'met with', 'n': 243}
{'person': 'Jeffrey Epstein', 'action': 'forwarded email to', 'n': 230}
{'person': 'Jeffrey Epstein', 'action': 'commented on', 'n': 158}
{'person': 'Jeffrey Epstein', 'action': 'sent email response to', 'n': 140}
{'person': 'Jeffrey Epstein', 'action': 'paid', 'n': 120}
{'person': 'Jeffrey Epstein', 'action': 'inquired about', 'n': 116}
{'person': 'Jeffrey Epstein', 'action': 'mentioned', 'n': 110}
{'person': 'Jeffrey Epstein', 'action': 'owns', 'n': 108}
{'person': 'Jeffrey Epstein', 'action': 'pleaded guilty to', 'n': 106}
{'person': 'Jeffrey Epstein', 'action': 'informed', 'n': 98}
{'person': 'Jeffrey Epstein', 'action': 'shared article about', 'n': 95}
{'person': 'Jeffrey Epstein', 'action': 'issued confidentiality notice', 'n': 94}
{'person': 'Jeffrey Epstein', 'action': 'asserted ownership of', 'n': 94}
{'person': 'Jeffrey Epstein', 'action': 'shared article with', 'n': 85}
{'person': 'Jeffrey Epstein', 'action': 'asked about', 'n': 81}
{'person': 'Jeffrey Epstein', 'action': 'responded to email from', 'n': 70}
{'person': 'Jeffrey Epstein', 'action': 'asked', 'n': 68}
{'person': 'Jeffrey Epstein', 'action': 'referenced', 'n': 67}
{'person': 'Jeffrey Epstein', 'action': 'represented', 'n': 65}
{'person': 'Jeffrey Epstein', 'action': 'claimed ownership of', 'n': 63}
{'person': 'Jeffrey Epstein', 'action': 'filed lawsuit against', 'n': 61}
{'person': 'Jeffrey Epstein', 'action': 'associated with', 'n': 61}
{'person': 'Jeffrey Epstein', 'action': 'called', 'n': 60}
{'person': 'Jeffrey Epstein', 'action': 'traveled with', 'n': 60}
{'person': 'Jeffrey Epstein', 'action': 'sent follow-up email to', 'n': 58}
{'person': 'Jeffrey Epstein', 'action': 'sued', 'n': 58}
{'person': 'Jeffrey Epstein', 'action': 'investigated', 'n': 57}
{'person': 'Jeffrey Epstein', 'action': 'proposed meeting with', 'n': 56}
{'person': 'Jeffrey Epstein', 'action': 'stated', 'n': 56}
{'person': 'Jeffrey Epstein', 'action': 'visited', 'n': 56}
{'person': 'Jeffrey Epstein', 'action': 'sent message about', 'n': 54}
{'person': 'Jeffrey Epstein', 'action': 'hosted', 'n': 53}
{'person': 'Jeffrey Epstein', 'action': 'questioned', 'n': 51}
{'person': 'Jeffrey Epstein', 'action': 'advised', 'n': 51}
{'person': 'Jeffrey Epstein', 'action': 'sent iMessage to', 'n': 48}
{'person': 'Jeffrey Epstein', 'action': 'sent email reply to', 'n': 48}
{'person': 'Jeffrey Epstein', 'action': 'replied to email from', 'n': 48}
{'person': 'Jeffrey Epstein', 'action': 'invited', 'n': 48}
{'person': 'Jeffrey Epstein', 'action': 'responded to', 'n': 47}
{'person': 'Jeffrey Epstein', 'action': 'discussed', 'n': 47}
{'person': 'Jeffrey Epstein', 'action': 'thanked', 'n': 46}
{'person': 'Jeffrey Epstein', 'action': 'issued confidentiality notice for', 'n': 46}
{'person': 'Jeffrey Epstein', 'action': 'sent message regarding', 'n': 46}
{'person': 'Jeffrey Epstein', 'action': 'criticized', 'n': 45}
{'person': 'Jeffrey Epstein', 'action': 'traveled to', 'n': 44}
{'person': 'Jeffrey Epstein', 'action': 'acknowledged', 'n': 43}
{'person': 'Jeffrey Epstein', 'action': 'defended', 'n': 42}
{'person': 'Jeffrey Epstein', 'action': 'described', 'n': 41}
{'person': 'Jeffrey Epstein', 'action': 'hired', 'n': 41}
{'person': 'Jeffrey Epstein', 'action': 'sexually abused', 'n': 38}
{'person': 'Jeffrey Epstein', 'action': 'owned', 'n': 37}
{'person': 'Jeffrey Epstein', 'action': 'asserted confidentiality of', 'n': 34}
{'person': 'Jeffrey Epstein', 'action': 'issued confidentiality notice to', 'n': 34}
{'person': 'Jeffrey Epstein', 'action': 'forwarded article to', 'n': 34}
{'person': 'Jeffrey Epstein', 'action': 'employed', 'n': 32}
{'person': 'Jeffrey Epstein', 'action': 'attended', 'n': 32}
{'person': 'Jeffrey Epstein', 'action': 'sent email message', 'n': 32}
{'person': 'Jeffrey Epstein', 'action': 'planned travel to', 'n': 32}
{'person': 'Jeffrey Epstein', 'action': 'flew', 'n': 32}
{'person': 'Jeffrey Epstein', 'action': 'asserts ownership of', 'n': 31}
{'person': 'Jeffrey Epstein', 'action': 'sexually assaulted', 'n': 31}
{'person': 'Jeffrey Epstein', 'action': 'reported', 'n': 29}
{'person': 'Jeffrey Epstein', 'action': 'responded via email to', 'n': 29}
{'person': 'Jeffrey Epstein', 'action': 'funded', 'n': 28}
{'person': 'Jeffrey Epstein', 'action': 'requested notification to', 'n': 28}
{'person': 'Jeffrey Epstein', 'action': 'received email from', 'n': 27}
{'person': 'Jeffrey Epstein', 'action': 'congratulated', 'n': 27}
{'person': 'Jeffrey Epstein', 'action': 'praised', 'n': 26}
{'person': 'Jeffrey Epstein', 'action': 'asserted', 'n': 26}
{'person': 'Jeffrey Epstein', 'action': 'served', 'n': 26}
{'person': 'Jeffrey Epstein', 'action': 'discussed with', 'n': 26}
{'person': 'Jeffrey Epstein', 'action': 'sent email regarding', 'n': 26}
{'person': 'Jeffrey Epstein', 'action': 'affirmed', 'n': 25}
{'person': 'Jeffrey Epstein', 'action': 'indicted', 'n': 24}
{'person': 'Jeffrey Epstein', 'action': 'donated', 'n': 24}
{'person': 'Jeffrey Epstein', 'action': 'claims ownership of', 'n': 24}
{'person': 'Jeffrey Epstein', 'action': 'befriended', 'n': 24}
{'person': 'Jeffrey Epstein', 'action': 'instructed', 'n': 24}
{'person': 'Jeffrey Epstein', 'action': 'sent email message to', 'n': 23}
{'person': 'Jeffrey Epstein', 'action': 'suggested meeting with', 'n': 23}
{'person': 'Jeffrey Epstein', 'action': 'donated to', 'n': 21}
{'person': 'Jeffrey Epstein', 'action': 'wrote article about', 'n': 21}
{'person': 'Jeffrey Epstein', 'action': 'sent instant message to', 'n': 21}
{'person': 'Jeffrey Epstein', 'action': 'published article about', 'n': 21}
{'person': 'Jeffrey Epstein', 'action': 'represents', 'n': 21}
{'person': 'Jeffrey Epstein', 'action': 'shared news article with', 'n': 21}
{'person': 'Jeffrey Epstein', 'action': 'claimed', 'n': 20}
{'person': 'Jeffrey Epstein', 'action': 'shared link to', 'n': 20}
{'person': 'Jeffrey Epstein', 'action': 'requested', 'n': 20}
{'person': 'Jeffrey Epstein', 'action': 'served as legal counsel for', 'n': 20}
{'person': 'Jeffrey Epstein', 'action': 'paid legal representation for', 'n': 20}
{'person': 'Jeffrey Epstein', 'action': 'sent message', 'n': 20}
{'person': 'Jeffrey Epstein', 'action': 'shared article link with', 'n': 19}
{'person': 'Jeffrey Epstein', 'action': 'joined', 'n': 19}
{'person': 'Jeffrey Epstein', 'action': 'requested meeting with', 'n': 19}
{'person': 'Jeffrey Epstein', 'action': 'introduced', 'n': 19}
{'person': 'Jeffrey Epstein', 'action': 'testified about', 'n': 19}
{'person': 'Jeffrey Epstein', 'action': 'noted', 'n': 19}
{'person': 'Jeffrey Epstein', 'action': 'planned meeting with', 'n': 19}
{'person': 'Jeffrey Epstein', 'action': 'replied to', 'n': 18}
{'person': 'Jeffrey Epstein', 'action': 'sent confidential communication to', 'n': 18}
{'person': 'Jeffrey Epstein', 'action': 'engaged in sexual activity with', 'n': 18}
{'person': 'Jeffrey Epstein', 'action': 'sent text message to', 'n': 17}
{'person': 'Jeffrey Epstein', 'action': 'requested interview with', 'n': 17}
{'person': 'Jeffrey Epstein', 'action': 'filed complaint against', 'n': 17}
{'person': 'Jeffrey Epstein', 'action': 'told', 'n': 17}
{'person': 'Jeffrey Epstein', 'action': 'threatened', 'n': 17}
{'person': 'Jeffrey Epstein', 'action': 'warned', 'n': 17}
{'person': 'Jeffrey Epstein', 'action': 'requested comment from', 'n': 16}
{'person': 'Jeffrey Epstein', 'action': 'referenced article about', 'n': 16}
{'person': 'Jeffrey Epstein', 'action': 'sent', 'n': 16}
{'person': 'Jeffrey Epstein', 'action': 'communicated with', 'n': 16}
{'person': 'Jeffrey Epstein', 'action': 'replied via email to', 'n': 16}
{'person': 'Jeffrey Epstein', 'action': 'issued confidentiality notice regarding', 'n': 16}
{'person': 'Jeffrey Epstein', 'action': 'stated that', 'n': 16}
{'person': 'Jeffrey Epstein', 'action': 'proposed meeting', 'n': 16}
{'person': 'Jeffrey Epstein', 'action': 'expressed concern about', 'n': 16}
{'person': 'Jeffrey Epstein', 'action': 'provided financial support to', 'n': 16}
{'person': 'Jeffrey Epstein', 'action': 'expressed gratitude to', 'n': 16}
{'person': 'Jeffrey Epstein', 'action': 'offered to arrange meeting with', 'n': 15}
{'person': 'Jeffrey Epstein', 'action': 'asked about location', 'n': 15}
{'person': 'Jeffrey Epstein', 'action': 'provided massage to', 'n': 15}
{'person': 'Jeffrey Epstein', 'action': 'referred to', 'n': 15}
{'person': 'Jeffrey Epstein', 'action': 'issued confidentiality notice on', 'n': 15}
{'person': 'Jeffrey Epstein', 'action': 'asserted confidentiality', 'n': 15}
{'person': 'Jeffrey Epstein', 'action': 'socialized with', 'n': 15}
{'person': 'Jeffrey Epstein', 'action': 'dined with', 'n': 15}
{'person': 'Jeffrey Epstein', 'action': 'reported on', 'n': 15}
{'person': 'Jeffrey Epstein', 'action': 'shared article link about', 'n': 15}
{'person': 'Jeffrey Epstein', 'action': 'sent email', 'n': 15}
{'person': 'Jeffrey Epstein', 'action': 'sent link to', 'n': 15}
{'person': 'Jeffrey Epstein', 'action': 'represented by', 'n': 15}
{'person': 'Jeffrey Epstein', 'action': 'commented', 'n': 14}
{'person': 'Jeffrey Epstein', 'action': 'identified', 'n': 14}
{'person': 'Jeffrey Epstein', 'action': 'sent email with article link to', 'n': 14}
{'person': 'Jeffrey Epstein', 'action': 'provided legal representation to', 'n': 14}
{'person': 'Jeffrey Epstein', 'action': 'reported to', 'n': 14}
{'person': 'Jeffrey Epstein', 'action': 'sent reply email to', 'n': 14}
{'person': 'Jeffrey Epstein', 'action': 'forwarded email from', 'n': 14}
{'person': 'Jeffrey Epstein', 'action': 'founded', 'n': 14}
{'person': 'Jeffrey Epstein', 'action': 'hosted meeting with', 'n': 14}
{'person': 'Jeffrey Epstein', 'action': 'sent email inquiry to', 'n': 14}
{'person': 'Jeffrey Epstein', 'action': 'suggested', 'n': 14}
{'person': 'Jeffrey Epstein', 'action': 'forwarded email chain to', 'n': 14}
{'person': 'Jeffrey Epstein', 'action': 'forwarded', 'n': 14}
{'person': 'Jeffrey Epstein', 'action': 'sent forwarded email to', 'n': 13}
{'person': 'Jeffrey Epstein', 'action': 'attended dinner with', 'n': 13}
{'person': 'Jeffrey Epstein', 'action': 'listed', 'n': 13}
{'person': 'Jeffrey Epstein', 'action': 'recruited', 'n': 13}
{'person': 'Jeffrey Epstein', 'action': 'had breakfast with', 'n': 13}
{'person': 'Jeffrey Epstein', 'action': 'apologized to', 'n': 13}
{'person': 'Jeffrey Epstein', 'action': 'negotiated non-prosecution agreement with', 'n': 13}
{'person': 'Jeffrey Epstein', 'action': 'suggested meeting', 'n': 13}
{'person': 'Jeffrey Epstein', 'action': 'walked with', 'n': 13}
{'person': 'Jeffrey Epstein', 'action': 'invoked Fifth Amendment rather than answer question about', 'n': 13}
{'person': 'Jeffrey Epstein', 'action': 'met', 'n': 13}
{'person': 'Jeffrey Epstein', 'action': 'maintained friendship with', 'n': 13}
{'person': 'Jeffrey Epstein', 'action': 'testified that', 'n': 13}
{'person': 'Jeffrey Epstein', 'action': 'owns property in', 'n': 13}
{'person': 'Jeffrey Epstein', 'action': 'sent_message', 'n': 13}
{'person': 'Jeffrey Epstein', 'action': 'sent email discussing', 'n': 13}
{'person': 'Jeffrey Epstein', 'action': 'provided information about', 'n': 12}
{'person': 'Jeffrey Epstein', 'action': 'cited', 'n': 12}
{'person': 'Jeffrey Epstein', 'action': 'informed about', 'n': 12}
{'person': 'Jeffrey Epstein', 'action': 'forwarded message to', 'n': 12}
{'person': 'Jeffrey Epstein', 'action': 'hired as legal counsel', 'n': 12}
{'person': 'Jeffrey Epstein', 'action': 'forwarded inquiry to', 'n': 12}
{'person': 'Jeffrey Epstein', 'action': 'was sentenced to', 'n': 12}
{'person': 'Jeffrey Epstein', 'action': 'forwarded allegations to', 'n': 12}
{'person': 'Jeffrey Epstein', 'action': 'invoked_fifth_amendment', 'n': 12}
{'person': 'Jeffrey Epstein', 'action': 'requested phone number from', 'n': 12}
{'person': 'Jeffrey Epstein', 'action': 'pledged funding to', 'n': 12}
{'person': 'Jeffrey Epstein', 'action': 'sent confidential communication', 'n': 12}
{'person': 'Jeffrey Epstein', 'action': 'photographed with', 'n': 12}
{'person': 'Jeffrey Epstein', 'action': 'signed non-prosecution agreement with', 'n': 12}
{'person': 'Jeffrey Epstein', 'action': 'gave massage to', 'n': 12}
{'person': 'Jeffrey Epstein', 'action': 'asserted confidentiality over', 'n': 11}
{'person': 'Jeffrey Epstein', 'action': 'possessed', 'n': 11}
{'person': 'Jeffrey Epstein', 'action': 'filed civil lawsuit against', 'n': 11}
{'person': 'Jeffrey Epstein', 'action': 'maintained contact information for', 'n': 11}
{'person': 'Jeffrey Epstein', 'action': 'confirmed', 'n': 11}
{'person': 'Jeffrey Epstein', 'action': 'attended event with', 'n': 11}
{'person': 'Jeffrey Epstein', 'action': 'forwarded media inquiry to', 'n': 11}
{'person': 'Jeffrey Epstein', 'action': 'received', 'n': 11}
{'person': 'Jeffrey Epstein', 'action': 'proposed meeting in', 'n': 11}
{'person': 'Jeffrey Epstein', 'action': 'reported that', 'n': 11}
{'person': 'Jeffrey Epstein', 'action': 'provided funding to', 'n': 11}
{'person': 'Jeffrey Epstein', 'action': 'registered as', 'n': 11}
{'person': 'Jeffrey Epstein', 'action': 'warned about', 'n': 11}
{'person': 'Jeffrey Epstein', 'action': 'born in', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'served as attorney for', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'sent email with link to', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'received call from', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'requested phone number', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'offered plea deal to', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'served as legal counsel to', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'refused to answer', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'flew on', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'sent invitation to', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'received massage from', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'joined board of', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'negotiated plea deal with', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'denied', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'responded affirmatively to', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'paid money to', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'asked for clarification', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'photographed', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'shared article', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'worked for', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'trafficked', 'n': 10}
{'person': 'Jeffrey Epstein', 'action': 'shared link', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'predicted price increase for', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'maintained relationship with', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'issued', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'traveled on aircraft with', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'suggested contacting', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'commented about', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'alerted', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'consulted with', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'contacted', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'commented that', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'arranged meeting with', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'paid settlement to', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'coordinated with', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'proposed meeting time', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'initiated call with', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'bought', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'requested contact information from', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'filed motion for summary judgment', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'confirmed meeting time', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'made public statement about', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'supported', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'interviewed', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'left', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'confirmed meeting', 'n': 9}
{'person': 'Jeffrey Epstein', 'action': 'recruited girls for', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'authored', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'served sentence of', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'forwarded article about', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'took the Fifth', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'sent message referencing', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'made allegations against', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'paid for sexual services from', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'sent article link to', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'inquired about schedule', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'provided legal defense for', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'shared information with', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'was born in', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'introduced young women to', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'issued confidentiality disclaimer', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'confirmed meeting time with', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'provided phone number to', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'sent response email to', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'dated', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'signed', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'maintained contacts with', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'requested information from', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'shared link about', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'offered', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'molested', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'sent inquiry to', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'pleaded_guilty_to', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'shared article link', 'n': 8}
{'person': 'Jeffrey Epstein', 'action': 'expressed concern to', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'confirmed availability', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'shared link with', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'attempted to recruit', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'sent brief message', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'participated in', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'provided information to', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'introduced to', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'acknowledged receipt', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'proposed travel to', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'predicted', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'shared information about', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'agreed with', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'released from', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'sent email asking about', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'invited to visit', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'settled', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'provided phone number', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'was released from', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'entered', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'flew with', 'n': 7}
{'person': 'Jeffrey Epstein', 'action': 'planned to attend', 'n': 7}

## 2.Step 2: bridge nodes analysis (as Lowie did before)
### 2.a. Who traveled with Epstein specifically? 
Search with edges: undirected, deduplicated.  
Travel network = proxy for social network. 
Travel connections directly linked to Epstein himself. NOTE: use of Aliases and duplicate nodes of Epstein himself.

## EXPLORATORY elements

In [26]:
# which entity types are actually exiting? 
run_print("""
MATCH (e:Entity)
WHERE e.entity_type IS NOT NULL
RETURN DISTINCT e.entity_type
ORDER BY e.entity_type
LIMIT 100
""")

{'e.entity_type': 'BDSM practitioner'}
{'e.entity_type': 'Chinese publisher'}
{'e.entity_type': 'NSA staff member'}
{'e.entity_type': 'NSA_security_officer'}
{'e.entity_type': 'Palestinian assailant'}
{'e.entity_type': 'Soviet_defector'}
{'e.entity_type': 'abuser'}
{'e.entity_type': 'academic'}
{'e.entity_type': 'academic administrator'}
{'e.entity_type': 'academic or activist'}
{'e.entity_type': 'academic or researcher'}
{'e.entity_type': 'academic researcher'}
{'e.entity_type': 'academic researcher or technology theorist'}
{'e.entity_type': 'academic researchers'}
{'e.entity_type': 'academic_administrator'}
{'e.entity_type': 'academic_author'}
{'e.entity_type': 'academic_economist'}
{'e.entity_type': 'academic_expert'}
{'e.entity_type': 'academic_faculty'}
{'e.entity_type': 'academic_lecturer'}
{'e.entity_type': 'academic_mentor'}
{'e.entity_type': 'academic_or_policy_analyst'}
{'e.entity_type': 'academic_or_scientist'}
{'e.entity_type': 'academic_researcher'}
{'e.entity_type': 'academic_staff_member'}
{'e.entity_type': 'accomplice'}
{'e.entity_type': 'accused'}
{'e.entity_type': 'accused_offender'}
{'e.entity_type': 'accuser'}
{'e.entity_type': 'acquaintance'}
{'e.entity_type': 'acquaintance or associate'}
{'e.entity_type': 'acquaintance or colleague'}
{'e.entity_type': 'acquaintance or contact'}
{'e.entity_type': 'acquaintance or friend'}
{'e.entity_type': 'acquaintance_or_associate'}
{'e.entity_type': 'acquaintance_or_friend'}
{'e.entity_type': 'activism_participants'}
{'e.entity_type': 'activist'}
{'e.entity_type': 'activist_organization'}
{'e.entity_type': 'actor'}
{'e.entity_type': 'actress'}
{'e.entity_type': 'administrative staff or office worker'}
{'e.entity_type': 'adult'}
{'e.entity_type': 'alleged abuser'}
{'e.entity_type': 'alleged minor victim'}
{'e.entity_type': 'alleged perpetrator'}
{'e.entity_type': 'alleged victim'}
{'e.entity_type': 'alleged_perpetrator'}
{'e.entity_type': 'alleged_victim'}
{'e.entity_type': 'analyst'}
{'e.entity_type': 'analyst or investigator'}
{'e.entity_type': 'animal'}
{'e.entity_type': 'anonymous commenter'}
{'e.entity_type': 'anonymous_commenter'}
{'e.entity_type': 'archaeologist'}
{'e.entity_type': 'armed militant'}
{'e.entity_type': 'armed_civilian_or_security_personnel'}
{'e.entity_type': 'artist'}
{'e.entity_type': 'assailant'}
{'e.entity_type': 'assistant'}
{'e.entity_type': 'associate'}
{'e.entity_type': 'associate or agent of Jeffrey Epstein'}
{'e.entity_type': 'associate or colleague'}
{'e.entity_type': 'associate or enforcer'}
{'e.entity_type': 'associate or political observer'}
{'e.entity_type': 'associate or staff member'}
{'e.entity_type': 'associate_of_epstein'}
{'e.entity_type': 'associate_or_confidant'}
{'e.entity_type': 'associate_or_dependent'}
{'e.entity_type': 'athlete'}
{'e.entity_type': 'attacker'}
{'e.entity_type': 'attorney'}
{'e.entity_type': 'audience member'}
{'e.entity_type': 'audience_member'}
{'e.entity_type': 'author'}
{'e.entity_type': 'bank executive'}
{'e.entity_type': 'benefactor'}
{'e.entity_type': 'board member'}
{'e.entity_type': 'board_member'}
{'e.entity_type': 'boat_owner'}
{'e.entity_type': 'business associate'}
{'e.entity_type': 'business associate or acquaintance'}
{'e.entity_type': 'business associate or financial advisor'}
{'e.entity_type': 'business associate or financial contact'}
{'e.entity_type': 'business associate or government official'}
{'e.entity_type': 'business associate or legal advisor'}
{'e.entity_type': 'business associate or media contact'}
{'e.entity_type': 'business associate or political figure'}
{'e.entity_type': 'business associate or political operative'}
{'e.entity_type': 'business associate or staff member'}
{'e.entity_type': 'business associate, political operator'}
{'e.entity_type': 'business entity'}
{'e.entity_type': 'business executive'}
{'e.entity_type': 'business magnate'}
{'e.entity_type': 'business operator'}
{'e.entity_type': 'business owner'}
{'e.entity_type': 'business owner or plaintiff'}
{'e.entity_type': 'business principal'}
{'e.entity_type': 'business principal or executive'}
{'e.entity_type': 'business professional'}